[versions]
agp = "8.5.2"

[libraries]
appcompat = "androidx.appcompat:appcompat:1.7.0" # Hoặc phiên bản mới nhất
material = "com.google.android.material:material:1.12.0" # Hoặc phiên bản mới nhất
activity = "androidx.activity:activity-ktx:1.9.1" # Hoặc phiên bản mới nhất
constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4" # Hoặc phiên bản mới nhất
junit = "junit:junit:4.13.2" # Hoặc phiên bảnmới nhất
extJunit = "androidx.test.ext:junit:1.2.1" # Hoặc phiên bản mới nhất
espressoCore = "androidx.test.espresso:espresso-core:3.6.1" # Hoặc phiên bản mới nhất
gson = "com.google.code.gson:gson:2.10.1" # Hoặc phiên bản mới nhất
retrofit = "com.squareup.retrofit2:retrofit:2.9.0" # Hoặc phiên bản mới nhất
retrofitConverterGson = "com.squareup.retrofit2:converter-gson:2.9.0" # Hoặc phiên bản mới nhất
rxjava = "io.reactivex.rxjava3:rxjava:3.1.5" # Hoặc phiên bản mới nhất
rxandroid = "io.reactivex.rxjava3:rxandroid:3.0.2" # Hoặc phiên bản mới nhất
retrofitAdapterRxjava3 = "com.squareup.retrofit2:adapter-rxjava3:2.9.0" # Hoặc phiên bản mới nhất
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

